# -*- coding: utf-8 -*-
"""hih2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtJKwSVGlyvSWCkhviZuJ8sTpM6exhOG
"""


# ============================================================
# CELL 1 — ENVIRONMENT CHECK
# ============================================================

import json
import math
import os
import random
import sys
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

warnings.filterwarnings("ignore")

print("=" * 70)
print("PYTHON:", sys.version)
print("PYTORCH:", torch.__version__)
print("=" * 70)

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA:", torch.version.cuda)
    print(
        "GPU Memory:",
        round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
        "GB"
    )
else:
    print("WARNING: CUDA is not available. Kaggle GPU is not enabled.")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("\nUsing device:", DEVICE)

# ============================================================
# CELL 2 — CONFIGURATION (FIXED FOR STABILITY)
# ============================================================

from pathlib import Path

# Automatically search Kaggle input
INPUT_ROOT = Path("/kaggle/input")

# Where we save models/results
OUTPUT_ROOT = Path("/kaggle/working/voice_deepfake_detector")
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

CHECKPOINT_DIR = OUTPUT_ROOT / "checkpoints"
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

# -----------------------------
# Audio configuration
# -----------------------------

SAMPLE_RATE = 16_000

# FoR "for-2sec" dataset
AUDIO_DURATION = 2.0
NUM_SAMPLES = int(SAMPLE_RATE * AUDIO_DURATION)

# Mel spectrogram
N_MELS = 128
N_FFT = 1024
HOP_LENGTH = 256
WIN_LENGTH = 1024

F_MIN = 20
F_MAX = SAMPLE_RATE // 2

# -----------------------------
# Training - Reduced LR for stability
# -----------------------------

BATCH_SIZE = 32
NUM_EPOCHS = 20

# Lowered from 3e-4 to 1e-4 to prevent NaN loss
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4

NUM_WORKERS = 2

# Gradient clipping
MAX_GRAD_NORM = 1.0

# Early stopping
PATIENCE = 5

# Mixed precision
USE_AMP = torch.cuda.is_available()

# -----------------------------
# Reproducibility
# -----------------------------

SEED = 42

print("Output:", OUTPUT_ROOT)
print("Sample rate:", SAMPLE_RATE)
print("New Learning Rate:", LEARNING_RATE)
print("AMP:", USE_AMP)

# ============================================================
# CELL 3 — FIND DATASET
# ============================================================

from pathlib import Path

# Safely locate dataset root without crashing on undefined variables
if globals().get("mohammedabdeldayem_the_fake_or_real_dataset_path"):
    INPUT_ROOT = Path(globals()["mohammedabdeldayem_the_fake_or_real_dataset_path"])
elif "DATASET_PATH" in os.environ:
    INPUT_ROOT = Path(os.environ["DATASET_PATH"])
else:
    # Check default Kaggle input or local directories
    possible_roots = [
        Path("/kaggle/input/the-fake-or-real-dataset"),
        Path("/kaggle/input/for-2sec"),
        Path("/kaggle/input"),
        Path("./dataset"),
        Path(".")
    ]
    INPUT_ROOT = next((p for p in possible_roots if p.exists() and any(p.rglob("*training*"))), Path("/kaggle/input"))

def find_split_directory(root: Path, split_name: str):
    """
    Search recursively for a directory containing:
        fake/
        real/
    and whose path contains the requested split name.
    """

    candidates = []

    for p in root.rglob("*"):
        if not p.is_dir():
            continue

        name = p.name.lower()

        if name != split_name.lower():
            continue

        fake_dir = p / "fake"
        real_dir = p / "real"

        if fake_dir.exists() and real_dir.exists():
            candidates.append(p)

    return candidates


train_candidates = find_split_directory(INPUT_ROOT, "training")
val_candidates   = find_split_directory(INPUT_ROOT, "validation")
test_candidates  = find_split_directory(INPUT_ROOT, "testing")

print("Training candidates:")
for p in train_candidates:
    print(" ", p)

print("\nValidation candidates:")
for p in val_candidates:
    print(" ", p)

print("\nTesting candidates:")
for p in test_candidates:
    print(" ", p)


if not train_candidates:
    raise FileNotFoundError(
        "Could not automatically find training/fake + training/real."
    )

TRAIN_DIR = train_candidates[0]
VAL_DIR = val_candidates[0]
TEST_DIR = test_candidates[0]

print("\n" + "=" * 70)
print("SELECTED DATASET")
print("=" * 70)

print("TRAIN:", TRAIN_DIR)
print("VAL  :", VAL_DIR)
print("TEST :", TEST_DIR)

# ============================================================
# CELL 4 — DATASET INSPECTION
# ============================================================

AUDIO_EXTENSIONS = {
    ".wav",
    ".flac",
    ".mp3",
    ".ogg",
    ".m4a"
}


def collect_files(split_dir):
    files = []

    for label_name, label in [
        ("real", 0),
        ("fake", 1)
    ]:
        directory = split_dir / label_name

        if not directory.exists():
            continue

        for file in directory.rglob("*"):
            if file.is_file() and file.suffix.lower() in AUDIO_EXTENSIONS:
                files.append((str(file), label))

    return files


train_files = collect_files(TRAIN_DIR)
val_files = collect_files(VAL_DIR)
test_files = collect_files(TEST_DIR)

print("=" * 70)
print("DATASET SIZE")
print("=" * 70)

print(f"Training   : {len(train_files):,}")
print(f"Validation : {len(val_files):,}")
print(f"Testing    : {len(test_files):,}")

print("\nClass distribution:")

for name, files in [
    ("TRAIN", train_files),
    ("VAL", val_files),
    ("TEST", test_files)
]:
    labels = [label for _, label in files]

    real_count = labels.count(0)
    fake_count = labels.count(1)

    print(
        f"{name:5s} | "
        f"REAL: {real_count:,} | "
        f"FAKE: {fake_count:,}"
    )

# ============================================================
# CELL 5 — AUDIO LOADER
# ============================================================

import soundfile as sf
from scipy.signal import resample_poly


def load_audio(path, target_sr=SAMPLE_RATE, training=False):
    """
    Load audio, convert to mono, resample if necessary,
    then force exactly NUM_SAMPLES samples (with random crop during training).
    """

    audio, sr = sf.read(path, dtype="float32", always_2d=False)

    # Convert stereo -> mono
    if audio.ndim == 2:
        audio = np.mean(audio, axis=1)

    audio = np.asarray(audio, dtype=np.float32)

    # Replace invalid values
    audio = np.nan_to_num(
        audio,
        nan=0.0,
        posinf=0.0,
        neginf=0.0
    )

    # Resample if required
    if sr != target_sr:

        gcd = math.gcd(int(sr), int(target_sr))

        up = target_sr // gcd
        down = sr // gcd

        audio = resample_poly(
            audio,
            up,
            down
        ).astype(np.float32)

    # Remove DC offset
    if len(audio) > 0:
        audio = audio - np.mean(audio)

    # Normalize safely
    max_abs = np.max(np.abs(audio)) if len(audio) else 0

    if max_abs > 1e-8:
        audio = audio / max_abs

    # Force exactly NUM_SAMPLES (2 seconds)
    if len(audio) < NUM_SAMPLES:

        audio = np.pad(
            audio,
            (0, NUM_SAMPLES - len(audio))
        )

    elif len(audio) > NUM_SAMPLES:

        if training:
            # Random crop during training to capture speech anywhere in the clip
            start = random.randint(0, len(audio) - NUM_SAMPLES)
            audio = audio[start : start + NUM_SAMPLES]
        else:
            # Consistent start crop for validation and testing
            audio = audio[:NUM_SAMPLES]

    return audio.astype(np.float32)

# ============================================================
# CELL 6 — MEL FILTER BANK
# ============================================================

def hz_to_mel(hz):
    return 2595.0 * np.log10(1.0 + hz / 700.0)


def mel_to_hz(mel):
    return 700.0 * (10.0 ** (mel / 2595.0) - 1.0)


def create_mel_filterbank(
    sample_rate,
    n_fft,
    n_mels,
    f_min,
    f_max
):

    # Mel points
    mel_min = hz_to_mel(f_min)
    mel_max = hz_to_mel(f_max)

    mel_points = np.linspace(
        mel_min,
        mel_max,
        n_mels + 2
    )

    hz_points = mel_to_hz(mel_points)

    # FFT frequencies
    fft_freqs = np.linspace(
        0,
        sample_rate / 2,
        n_fft // 2 + 1
    )

    filterbank = np.zeros(
        (n_mels, n_fft // 2 + 1),
        dtype=np.float32
    )

    for m in range(1, n_mels + 1):

        left = hz_points[m - 1]
        center = hz_points[m]
        right = hz_points[m + 1]

        # Rising slope
        left_indices = np.where(
            (fft_freqs >= left) &
            (fft_freqs <= center)
        )[0]

        if center > left:
            filterbank[m - 1, left_indices] = (
                (fft_freqs[left_indices] - left) /
                (center - left)
            )

        # Falling slope
        right_indices = np.where(
            (fft_freqs >= center) &
            (fft_freqs <= right)
        )[0]

        if right > center:
            filterbank[m - 1, right_indices] = (
                (right - fft_freqs[right_indices]) /
                (right - center)
            )

    return torch.tensor(filterbank, dtype=torch.float32)


MEL_FILTERBANK = create_mel_filterbank(
    SAMPLE_RATE,
    N_FFT,
    N_MELS,
    F_MIN,
    F_MAX
)

print("Mel filterbank:", MEL_FILTERBANK.shape)

# ============================================================
# CELL 7 — PYTORCH DATASET
# ============================================================

class VoiceDataset(Dataset):

    def __init__(
        self,
        files,
        training=False
    ):

        self.files = files
        self.training = training

    def __len__(self):
        return len(self.files)

    def waveform_augmentation(self, audio):

        audio = torch.from_numpy(audio)

        # ------------------------------------
        # Random gain
        # ------------------------------------

        if random.random() < 0.5:

            gain_db = random.uniform(-3.0, 3.0)

            gain = 10 ** (gain_db / 20.0)

            audio = audio * gain

        # ------------------------------------
        # Random noise
        # ------------------------------------

        if random.random() < 0.30:

            noise_level = random.uniform(
                0.001,
                0.01
            )

            noise = torch.randn_like(audio)

            audio = audio + noise_level * noise

        # ------------------------------------
        # Small time shift
        # ------------------------------------

        if random.random() < 0.30:

            shift = random.randint(
                -800,
                800
            )

            audio = torch.roll(
                audio,
                shifts=shift,
                dims=0
            )

        # ------------------------------------
        # Clamp
        # ------------------------------------

        audio = torch.clamp(
            audio,
            -1.0,
            1.0
        )

        return audio

    def __getitem__(self, index):

        path, label = self.files[index]

        audio = load_audio(path, training=self.training)

        # Augment only training data
        if self.training:
            audio = self.waveform_augmentation(audio)
        else:
            audio = torch.from_numpy(audio)

        return audio, torch.tensor(
            label,
            dtype=torch.float32
        ), path


train_dataset = VoiceDataset(
    train_files,
    training=True
)

val_dataset = VoiceDataset(
    val_files,
    training=False
)

test_dataset = VoiceDataset(
    test_files,
    training=False
)

print("Datasets created.")

# ============================================================
# CELL 8 — DATALOADERS
# ============================================================

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
    persistent_workers=(NUM_WORKERS > 0),
    drop_last=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
    persistent_workers=(NUM_WORKERS > 0)
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
    persistent_workers=(NUM_WORKERS > 0)
)

print("Train batches:", len(train_loader))
print("Val batches:", len(val_loader))
print("Test batches:", len(test_loader))

# ============================================================
# CELL 9 — GPU MEL SPECTROGRAM
# ============================================================

class LogMelSpectrogram(nn.Module):

    def __init__(
        self,
        sample_rate,
        n_fft,
        hop_length,
        win_length,
        n_mels,
        mel_filterbank
    ):

        super().__init__()

        self.n_fft = n_fft
        self.hop_length = hop_length
        self.win_length = win_length

        window = torch.hann_window(
            win_length
        )

        self.register_buffer(
            "window",
            window
        )

        self.register_buffer(
            "mel_filterbank",
            mel_filterbank
        )

    def forward(self, waveform):

        # waveform: [B, T]
        # Force FP32 computation to completely prevent FP16 underflow/NaNs during STFT & log-mel
        with torch.cuda.amp.autocast(enabled=False):
            waveform = waveform.float()

            stft = torch.stft(
                waveform,
                n_fft=self.n_fft,
                hop_length=self.hop_length,
                win_length=self.win_length,
                window=self.window,
                center=True,
                return_complex=True
            )

            # Magnitude
            magnitude = torch.abs(stft)

            # Power
            power = magnitude ** 2

            # Mel projection
            mel = torch.matmul(
                self.mel_filterbank,
                power
            )

            # Log scale: clamp min=1e-5 to guarantee finite log values (prevents -inf / NaN)
            mel = torch.log(
                torch.clamp(mel, min=1e-5)
            )

            # Per-example normalization (Mean-Variance Normalization)
            mean = mel.mean(
                dim=(-2, -1),
                keepdim=True
            )

            std = mel.std(
                dim=(-2, -1),
                keepdim=True
            )

            mel = (mel - mean) / (
                std + 1e-5
            )

            # [B, 1, MELS, TIME]
            mel = mel.unsqueeze(1)

        return mel

# ============================================================
# CELL 10 — SPEC AUGMENT
# ============================================================

class SpecAugment(nn.Module):

    def __init__(
        self,
        freq_mask=12,
        time_mask=15
    ):

        super().__init__()

        self.freq_mask = freq_mask
        self.time_mask = time_mask

    def forward(self, x):

        if not self.training:
            return x

        B, C, FREQ, TIME = x.shape
        x = x.clone()

        # Apply masking per-sample independently across the batch
        for b in range(B):
            # Frequency masking
            for _ in range(2):

                width = random.randint(
                    0,
                    min(self.freq_mask, FREQ - 1)
                )

                if width > 0:

                    start = random.randint(
                        0,
                        FREQ - width
                    )

                    x[
                        b,
                        :,
                        start:start + width,
                        :
                    ] = 0.0

            # Time masking
            for _ in range(2):

                width = random.randint(
                    0,
                    min(self.time_mask, TIME - 1)
                )

                if width > 0:

                    start = random.randint(
                        0,
                        TIME - width
                    )

                    x[
                        b,
                        :,
                        :,
                        start:start + width
                    ] = 0.0

        return x

# ============================================================
# CELL 11 — MODEL
# ============================================================

class ConvBNAct(nn.Module):

    def __init__(
        self,
        in_channels,
        out_channels,
        kernel_size=3,
        stride=1,
        padding=1
    ):

        super().__init__()

        self.block = nn.Sequential(

            nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size,
                stride,
                padding,
                bias=False
            ),

            nn.BatchNorm2d(
                out_channels
            ),

            nn.SiLU(
                inplace=True
            )
        )

    def forward(self, x):
        return self.block(x)


class SEBlock(nn.Module):

    def __init__(
        self,
        channels,
        reduction=8
    ):

        super().__init__()

        hidden = max(
            channels // reduction,
            8
        )

        self.pool = nn.AdaptiveAvgPool2d(1)

        self.fc = nn.Sequential(

            nn.Linear(
                channels,
                hidden
            ),

            nn.SiLU(),

            nn.Linear(
                hidden,
                channels
            ),

            nn.Sigmoid()
        )

    def forward(self, x):

        b, c, _, _ = x.shape

        y = self.pool(x)
        y = y.flatten(1)
        y = self.fc(y)
        y = y.view(b, c, 1, 1)

        return x * y


class ResidualSEBlock(nn.Module):

    def __init__(
        self,
        in_channels,
        out_channels,
        stride=1,
        dropout=0.0
    ):

        super().__init__()

        self.conv1 = ConvBNAct(
            in_channels,
            out_channels,
            stride=stride
        )

        self.conv2 = nn.Sequential(

            nn.Conv2d(
                out_channels,
                out_channels,
                3,
                padding=1,
                bias=False
            ),

            nn.BatchNorm2d(
                out_channels
            )
        )

        self.se = SEBlock(
            out_channels
        )

        self.dropout = nn.Dropout2d(
            dropout
        )

        if (
            in_channels != out_channels
            or stride != 1
        ):

            self.shortcut = nn.Sequential(

                nn.Conv2d(
                    in_channels,
                    out_channels,
                    1,
                    stride=stride,
                    bias=False
                ),

                nn.BatchNorm2d(
                    out_channels
                )
            )

        else:

            self.shortcut = nn.Identity()

        self.activation = nn.SiLU(
            inplace=True
        )

    def forward(self, x):

        identity = self.shortcut(x)

        out = self.conv1(x)

        out = self.conv2(out)

        out = self.se(out)

        out = self.dropout(out)

        out = out + identity

        return self.activation(out)


class VoiceDeepfakeCNN(nn.Module):

    def __init__(self):

        super().__init__()

        self.features = nn.Sequential(

            ConvBNAct(
                1,
                32,
                kernel_size=5,
                stride=2,
                padding=2
            ),

            ResidualSEBlock(
                32,
                32,
                stride=1,
                dropout=0.05
            ),

            ResidualSEBlock(
                32,
                64,
                stride=2,
                dropout=0.05
            ),

            ResidualSEBlock(
                64,
                64,
                stride=1,
                dropout=0.05
            ),

            ResidualSEBlock(
                64,
                128,
                stride=2,
                dropout=0.10
            ),

            ResidualSEBlock(
                128,
                128,
                stride=1,
                dropout=0.10
            ),

            ResidualSEBlock(
                128,
                256,
                stride=2,
                dropout=0.15
            ),

            ResidualSEBlock(
                256,
                256,
                stride=1,
                dropout=0.15
            )
        )

        self.pool = nn.AdaptiveAvgPool2d(
            (1, 1)
        )

        self.classifier = nn.Sequential(

            nn.Flatten(),

            nn.Linear(
                256,
                128
            ),

            nn.SiLU(),

            nn.Dropout(
                0.35
            ),

            nn.Linear(
                128,
                1
            )
        )

    def forward(self, x):

        x = self.features(x)

        x = self.pool(x)

        x = self.classifier(x)

        return x.squeeze(-1)

# ============================================================
# CELL 12 — COMPLETE MODEL
# ============================================================

mel_transform = LogMelSpectrogram(
    sample_rate=SAMPLE_RATE,
    n_fft=N_FFT,
    hop_length=HOP_LENGTH,
    win_length=WIN_LENGTH,
    n_mels=N_MELS,
    mel_filterbank=MEL_FILTERBANK
).to(DEVICE)

spec_augment = SpecAugment(
    freq_mask=12,
    time_mask=15
).to(DEVICE)

model = VoiceDeepfakeCNN().to(DEVICE)

print(model)

total_params = sum(
    p.numel()
    for p in model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print("\nTotal parameters:", f"{total_params:,}")
print("Trainable parameters:", f"{trainable_params:,}")

# ============================================================
# CELL 13 — FORWARD PASS TEST
# ============================================================

model.eval()
mel_transform.eval()

audio_batch, labels, paths = next(
    iter(train_loader)
)

audio_batch = audio_batch.to(
    DEVICE,
    non_blocking=True
)

with torch.no_grad():

    mel = mel_transform(
        audio_batch
    )

    output = model(
        mel
    )

print("Audio:", audio_batch.shape)
print("Mel:", mel.shape)
print("Output:", output.shape)

print("\nSample logits:")
print(output[:5])

# ============================================================
# CELL 14 — METRICS
# ============================================================

from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, f1_score, precision_score,
                             recall_score, roc_auc_score, roc_curve)


def calculate_metrics(
    y_true,
    y_prob,
    threshold=0.5
):

    y_true = np.asarray(y_true)
    y_prob = np.asarray(y_prob)

    y_pred = (
        y_prob >= threshold
    ).astype(int)

    metrics = {}

    metrics["accuracy"] = accuracy_score(
        y_true,
        y_pred
    )

    metrics["precision"] = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    metrics["recall"] = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    metrics["f1"] = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    try:
        metrics["roc_auc"] = roc_auc_score(
            y_true,
            y_prob
        )
    except:
        metrics["roc_auc"] = 0.0

    return metrics


def find_best_threshold(
    y_true,
    y_prob
):

    thresholds = np.linspace(
        0.05,
        0.95,
        91
    )

    best_threshold = 0.5
    best_f1 = -1

    for threshold in thresholds:

        y_pred = (
            y_prob >= threshold
        ).astype(int)

        score = f1_score(
            y_true,
            y_pred,
            zero_division=0
        )

        if score > best_f1:

            best_f1 = score
            best_threshold = threshold

    return best_threshold, best_f1

# ============================================================
# CELL 15 — OPTIMIZER
# ============================================================

# Calculate class balance
train_labels = np.array(
    [label for _, label in train_files]
)

real_count = np.sum(
    train_labels == 0
)

fake_count = np.sum(
    train_labels == 1
)

# BCE positive-class weighting
pos_weight_value = (
    real_count / max(fake_count, 1)
)

pos_weight = torch.tensor(
    [pos_weight_value],
    dtype=torch.float32,
    device=DEVICE
)

criterion = nn.BCEWithLogitsLoss(
    pos_weight=pos_weight
)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
    optimizer,
    T_0=5,
    T_mult=2,
    eta_min=1e-6
)

scaler = torch.cuda.amp.GradScaler(
    enabled=USE_AMP
)

print("REAL:", real_count)
print("FAKE:", fake_count)
print("pos_weight:", pos_weight_value)
print("Optimizer ready.")

# ============================================================
# CELL 16 — TRAINING FUNCTION
# ============================================================

def train_one_epoch(
    model,
    loader,
    optimizer,
    criterion,
    epoch
):

    model.train()
    mel_transform.train()
    spec_augment.train()

    running_loss = 0.0

    all_probs = []
    all_labels = []

    start_time = time.time()

    for batch_idx, (
        audio,
        labels,
        _
    ) in enumerate(loader):

        audio = audio.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        with torch.cuda.amp.autocast(
            enabled=USE_AMP
        ):

            mel = mel_transform(
                audio
            )

            mel = spec_augment(
                mel
            )

            logits = model(
                mel
            )

            loss = criterion(
                logits,
                labels
            )

        scaler.scale(
            loss
        ).backward()

        scaler.unscale_(
            optimizer
        )

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            MAX_GRAD_NORM
        )

        scaler.step(
            optimizer
        )

        scaler.update()

        running_loss += (
            loss.item() *
            audio.size(0)
        )

        probs = torch.sigmoid(
            logits
        )

        all_probs.extend(
            probs.detach().cpu().numpy()
        )

        all_labels.extend(
            labels.detach().cpu().numpy()
        )

        # Scheduler
        scheduler.step(
            epoch +
            batch_idx / len(loader)
        )

        if batch_idx % 100 == 0:

            print(
                f"\rEpoch {epoch + 1} | "
                f"Batch {batch_idx}/{len(loader)} | "
                f"Loss {loss.item():.4f}",
                end=""
            )

    print()

    epoch_loss = (
        running_loss /
        len(loader.dataset)
    )

    metrics = calculate_metrics(
        all_labels,
        all_probs
    )

    elapsed = time.time() - start_time

    return epoch_loss, metrics, elapsed

# ============================================================
# CELL 17 — VALIDATION
# ============================================================

@torch.no_grad()
def evaluate(
    model,
    loader,
    criterion
):

    model.eval()
    mel_transform.eval()
    spec_augment.eval()

    running_loss = 0.0

    all_probs = []
    all_labels = []
    all_paths = []

    for audio, labels, paths in loader:

        audio = audio.to(
            DEVICE,
            non_blocking=True
        )

        labels = labels.to(
            DEVICE,
            non_blocking=True
        )

        with torch.cuda.amp.autocast(
            enabled=USE_AMP
        ):

            mel = mel_transform(
                audio
            )

            logits = model(
                mel
            )

            loss = criterion(
                logits,
                labels
            )

        running_loss += (
            loss.item() *
            audio.size(0)
        )

        probs = torch.sigmoid(
            logits
        )

        all_probs.extend(
            probs.cpu().numpy()
        )

        all_labels.extend(
            labels.cpu().numpy()
        )

        all_paths.extend(
            paths
        )

    epoch_loss = (
        running_loss /
        len(loader.dataset)
    )

    metrics = calculate_metrics(
        all_labels,
        all_probs
    )

    return (
        epoch_loss,
        metrics,
        np.array(all_labels),
        np.array(all_probs),
        all_paths
    )

# ============================================================
# CELL 18 — CHECKPOINT FUNCTIONS
# ============================================================

BEST_MODEL_PATH = (
    CHECKPOINT_DIR /
    "best_voice_deepfake_model.pth"
)

LAST_MODEL_PATH = (
    CHECKPOINT_DIR /
    "last_voice_deepfake_model.pth"
)


def save_checkpoint(
    path,
    epoch,
    model,
    optimizer,
    scheduler,
    best_score,
    threshold
):

    checkpoint = {

        "epoch": int(epoch),

        "model_state_dict":
            model.state_dict(),

        "optimizer_state_dict":
            optimizer.state_dict(),

        "scheduler_state_dict":
            scheduler.state_dict(),

        "best_score":
            float(best_score),

        "threshold":
            float(threshold),

        "config": {

            "sample_rate":
                SAMPLE_RATE,

            "duration":
                AUDIO_DURATION,

            "n_mels":
                N_MELS,

            "n_fft":
                N_FFT,

            "hop_length":
                HOP_LENGTH,

            "win_length":
                WIN_LENGTH
        }
    }

    torch.save(
        checkpoint,
        path
    )


def load_checkpoint(
    path
):

    checkpoint = torch.load(
        path,
        map_location=DEVICE
    )

    model.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )

    optimizer.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )

    scheduler.load_state_dict(
        checkpoint[
            "scheduler_state_dict"
        ]
    )

    return checkpoint

# ============================================================
# CELL 19 — TRAIN MODEL
# ============================================================

history = []

best_val_auc = -1.0
best_threshold = 0.5

epochs_without_improvement = 0

print("=" * 70)
print("STARTING TRAINING")
print("=" * 70)

print("Device:", DEVICE)
print("Epochs:", NUM_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Training samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))
print("=" * 70)


for epoch in range(NUM_EPOCHS):

    epoch_start = time.time()

    train_loss, train_metrics, train_time = train_one_epoch(
        model,
        train_loader,
        optimizer,
        criterion,
        epoch
    )

    (
        val_loss,
        val_metrics,
        val_labels,
        val_probs,
        _
    ) = evaluate(
        model,
        val_loader,
        criterion
    )

    # Find best threshold using validation set
    threshold, threshold_f1 = find_best_threshold(
        val_labels,
        val_probs
    )

    current_lr = optimizer.param_groups[0]["lr"]

    print("\n" + "=" * 70)

    print(
        f"Epoch {epoch + 1}/{NUM_EPOCHS}"
    )

    print(
        f"Time: {time.time() - epoch_start:.1f}s"
    )

    print(
        f"LR: {current_lr:.7f}"
    )

    print("\nTRAIN")
    print(
        f"Loss: {train_loss:.4f} | "
        f"Acc: {train_metrics['accuracy']:.4f} | "
        f"F1: {train_metrics['f1']:.4f} | "
        f"AUC: {train_metrics['roc_auc']:.4f}"
    )

    print("\nVALIDATION")
    print(
        f"Loss: {val_loss:.4f} | "
        f"Acc: {val_metrics['accuracy']:.4f} | "
        f"Precision: {val_metrics['precision']:.4f} | "
        f"Recall: {val_metrics['recall']:.4f} | "
        f"F1: {val_metrics['f1']:.4f} | "
        f"AUC: {val_metrics['roc_auc']:.4f}"
    )

    print(
        f"Best threshold on validation: "
        f"{threshold:.3f}"
    )

    # Save history
    history.append({

        "epoch": epoch + 1,

        "train_loss":
            train_loss,

        "val_loss":
            val_loss,

        "train_accuracy":
            train_metrics["accuracy"],

        "val_accuracy":
            val_metrics["accuracy"],

        "train_f1":
            train_metrics["f1"],

        "val_f1":
            val_metrics["f1"],

        "train_auc":
            train_metrics["roc_auc"],

        "val_auc":
            val_metrics["roc_auc"],

        "threshold":
            threshold,

        "lr":
            current_lr
    })

    # Save latest
    save_checkpoint(
        LAST_MODEL_PATH,
        epoch,
        model,
        optimizer,
        scheduler,
        best_val_auc,
        threshold
    )

    # ----------------------------------------
    # Best model
    # ----------------------------------------

    if val_metrics["roc_auc"] > best_val_auc:

        best_val_auc = (
            val_metrics["roc_auc"]
        )

        best_threshold = threshold

        epochs_without_improvement = 0

        save_checkpoint(
            BEST_MODEL_PATH,
            epoch,
            model,
            optimizer,
            scheduler,
            best_val_auc,
            best_threshold
        )

        print(
            f"\n🔥 NEW BEST MODEL!"
        )

        print(
            f"Validation ROC-AUC: "
            f"{best_val_auc:.4f}"
        )

    else:

        epochs_without_improvement += 1

        print(
            f"\nNo improvement "
            f"({epochs_without_improvement}/{PATIENCE})"
        )

    # Early stopping
    if epochs_without_improvement >= PATIENCE:

        print(
            "\n⛔ Early stopping triggered."
        )

        break


history_df = pd.DataFrame(
    history
)

history_df.to_csv(
    OUTPUT_ROOT /
    "training_history.csv",
    index=False
)

print("\n" + "=" * 70)
print("TRAINING COMPLETE")
print("=" * 70)

print(
    "Best validation AUC:",
    best_val_auc
)

print(
    "Best threshold:",
    best_threshold
)

print(
    "Model:",
    BEST_MODEL_PATH
)

# ============================================================
# CELL 20 — LOAD BEST MODEL
# ============================================================

import numpy as np
import torch

# Load checkpoint safely across PyTorch and NumPy versions
try:
    if hasattr(np, "_core"):
        torch.serialization.add_safe_globals([np._core.multiarray.scalar])
    elif hasattr(np, "core"):
        torch.serialization.add_safe_globals([np.core.multiarray.scalar])
except Exception:
    pass

checkpoint = torch.load(
    BEST_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

best_threshold = checkpoint.get(
    "threshold",
    0.5
)

print("Best model loaded.")
print("Best epoch:", checkpoint["epoch"] + 1)
print("Best validation AUC:", checkpoint["best_score"])
print("Decision threshold:", best_threshold)

import numpy as np
import torch

print("=" * 60)
print("MODEL HEALTH CHECK")
print("=" * 60)

bad_params = []

for name, param in model.named_parameters():
    if not torch.all(torch.isfinite(param)):
        bad_params.append(name)

if bad_params:
    print("❌ MODEL CONTAINS NaN/Inf PARAMETERS")
    print(f"Bad parameter tensors: {len(bad_params)}")

    for name in bad_params[:20]:
        print("  ", name)
else:
    print("✅ ALL MODEL PARAMETERS ARE FINITE")

print("=" * 60)

# Check parameter statistics
all_params = torch.cat([
    p.detach().float().flatten()
    for p in model.parameters()
])

print("Parameter min :", all_params.min().item())
print("Parameter max :", all_params.max().item())
print("Parameter mean:", all_params.mean().item())
print("Parameter std :", all_params.std().item())

print("=" * 60)

# ============================================================
# CELL 21 — TRAINING CURVES
# ============================================================

import matplotlib.pyplot as plt

history_df = pd.DataFrame(history)

plt.figure(figsize=(10, 5))

plt.plot(
    history_df["epoch"],
    history_df["train_loss"],
    label="Train Loss"
)

plt.plot(
    history_df["epoch"],
    history_df["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)

plt.show()


plt.figure(figsize=(10, 5))

plt.plot(
    history_df["epoch"],
    history_df["train_auc"],
    label="Train ROC-AUC"
)

plt.plot(
    history_df["epoch"],
    history_df["val_auc"],
    label="Validation ROC-AUC"
)

plt.xlabel("Epoch")
plt.ylabel("ROC-AUC")
plt.title("ROC-AUC")
plt.legend()
plt.grid(True)

plt.show()

# ============================================================
# TEST SET EVALUATION
# ============================================================

print("\n" + "=" * 70)
print("TEST SET EVALUATION")
print("=" * 70)

test_loss, test_metrics, test_labels, test_probs, test_paths = evaluate(
    model,
    test_loader,
    criterion
)

test_pred = (
    test_probs >= best_threshold
).astype(int)

test_auc = test_metrics.get("roc_auc", 0.0)

print(f"Test Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_metrics['accuracy']:.4f}")
print(f"Test Precision: {test_metrics['precision']:.4f}")
print(f"Test Recall    : {test_metrics['recall']:.4f}")
print(f"Test F1       : {test_metrics['f1']:.4f}")
print(f"Test ROC-AUC  : {test_auc:.4f}")
print("=" * 70)

labels = np.asarray(test_labels)
probs = np.asarray(test_probs)

print("================================")
print("TEST PREDICTION DIAGNOSTIC")
print("================================")
print("Samples:", len(probs))
print("NaN probabilities:", np.isnan(probs).sum())
print("Inf probabilities:", np.isinf(probs).sum())
print("NaN labels:", np.isnan(labels).sum())
print("Inf labels:", np.isinf(labels).sum())

if np.isfinite(probs).any():
    print("Min probability:", np.nanmin(probs))
    print("Max probability:", np.nanmax(probs))

print("================================")

# ============================================================
# CELL 22 — FINAL TEST
# ============================================================
print("=" * 60)
print("INPUT / SPECTROGRAM CHECK")
print("=" * 60)

model.eval()

batch = next(iter(test_loader))

# Depending on our dataset structure
if isinstance(batch, (list, tuple)):
    audio_batch = batch[0]
    labels_batch = batch[1]
else:
    audio_batch = batch["audio"]
    labels_batch = batch["label"]

audio_batch = audio_batch.to(DEVICE)

print("Audio shape:", audio_batch.shape)
print("Audio dtype:", audio_batch.dtype)

print("Audio NaN:", torch.isnan(audio_batch).sum().item())
print("Audio Inf:", torch.isinf(audio_batch).sum().item())

print("Audio min:", audio_batch.min().item())
print("Audio max:", audio_batch.max().item())

# ---------------------------------------------------------
# Generate spectrogram
# ---------------------------------------------------------

with torch.no_grad():
    mel = mel_transform(audio_batch)

print("\nMel shape:", mel.shape)
print("Mel NaN:", torch.isnan(mel).sum().item())
print("Mel Inf:", torch.isinf(mel).sum().item())

print("Mel min:", mel.min().item())
print("Mel max:", mel.max().item())

# ---------------------------------------------------------
# Model output
# ---------------------------------------------------------

with torch.no_grad():
    logits = model(mel)

print("\nLogits shape:", logits.shape)
print("Logits NaN:", torch.isnan(logits).sum().item())
print("Logits Inf:", torch.isinf(logits).sum().item())

if torch.isfinite(logits).any():
    print("Logit min:", logits.min().item())
    print("Logit max:", logits.max().item())

print("=" * 60)

# ============================================================
# CELL 23 — CONFUSION MATRIX
# ============================================================

from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(
    test_labels,
    test_pred
)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "REAL",
        "FAKE"
    ]
)

fig, ax = plt.subplots(
    figsize=(7, 7)
)

disp.plot(
    ax=ax,
    values_format="d"
)

plt.title(
    "Voice Deepfake Detector — Confusion Matrix"
)

plt.show()


print("\nClassification Report:\n")

print(
    classification_report(
        test_labels,
        test_pred,
        target_names=[
            "REAL",
            "FAKE"
        ],
        digits=4
    )
)

# ============================================================
# CELL 24 — ROC CURVE
# ============================================================

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import roc_curve

# Check if probabilities are valid before plotting
if np.isnan(test_probs).any():
    print("Cannot plot ROC curve: Model outputs contain NaN values.")
    print("Please re-train the model with stable hyperparameters (lower LR/gradient clipping).")
else:
    fpr, tpr, thresholds = roc_curve(
        test_labels,
        test_probs
    )

    plt.figure(figsize=(8, 7))

    plt.plot(
        fpr,
        tpr,
        label=f"ROC-AUC = {test_auc:.4f}"
    )

    plt.plot(
        [0, 1],
        [0, 1],
        linestyle="--"
    )

    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")

    plt.title(
        "ROC Curve — Voice Deepfake Detection"
    )

    plt.legend()
    plt.grid(True)

    plt.show()

# ============================================================
# CELL 25 — SINGLE AUDIO PREDICTION
# ============================================================

def predict_audio(
    audio_path,
    threshold=None
):

    if threshold is None:
        threshold = best_threshold

    model.eval()
    mel_transform.eval()

    audio = load_audio(
        audio_path
    )

    audio_tensor = torch.from_numpy(
        audio
    ).unsqueeze(0).to(
        DEVICE
    )

    with torch.no_grad():

        mel = mel_transform(
            audio_tensor
        )

        logits = model(
            mel
        )

        probability_fake = torch.sigmoid(
            logits
        ).item()

    probability_real = (
        1.0 - probability_fake
    )

    prediction = (
        "FAKE / SYNTHETIC"
        if probability_fake >= threshold
        else
        "REAL / BONAFIDE"
    )

    confidence = max(
        probability_fake,
        probability_real
    )

    return {
        "file": str(audio_path),
        "prediction": prediction,
        "fake_probability": probability_fake,
        "real_probability": probability_real,
        "confidence": confidence,
        "threshold": threshold
    }

# ============================================================
# CELL 26 — RANDOM TEST EXAMPLES
# ============================================================

random.seed(42)

samples_to_test = random.sample(
    test_files,
    min(10, len(test_files))
)

results = []

for path, actual_label in samples_to_test:

    result = predict_audio(path)

    result["actual"] = (
        "FAKE"
        if actual_label == 1
        else "REAL"
    )

    results.append(result)


results_df = pd.DataFrame(
    results
)

results_df[
    [
        "actual",
        "prediction",
        "real_probability",
        "fake_probability",
        "confidence",
        "file"
    ]
]

# ============================================================
# CELL 27 — TEST REAL AUDIO
# ============================================================

real_files = [
    path
    for path, label in test_files
    if label == 0
]

real_example = random.choice(
    real_files
)

real_result = predict_audio(
    real_example
)

print(json.dumps(
    real_result,
    indent=4
))

# ============================================================
# CELL 28 — TEST FAKE AUDIO
# ============================================================

fake_files = [
    path
    for path, label in test_files
    if label == 1
]

fake_example = random.choice(
    fake_files
)

fake_result = predict_audio(
    fake_example
)

print(json.dumps(
    fake_result,
    indent=4
))

# ============================================================
# CELL 29 — SAVE TEST PREDICTIONS
# ============================================================

prediction_df = pd.DataFrame({

    "file": test_paths,

    "actual": test_labels.astype(int),

    "fake_probability": test_probs,

    "real_probability": 1.0 - test_probs,

    "prediction": test_pred,

})

prediction_df.to_csv(
    OUTPUT_ROOT /
    "test_predictions.csv",
    index=False
)

print(
    "Saved:",
    OUTPUT_ROOT /
    "test_predictions.csv"
)

# ============================================================
# CELL 30 — SAVE DEPLOYMENT MODEL
# ============================================================

DEPLOYMENT_MODEL_PATH = (
    OUTPUT_ROOT /
    "voice_deepfake_detector.pth"
)

deployment_package = {

    "model_state_dict":
        model.state_dict(),

    "threshold":
        float(best_threshold),

    "sample_rate":
        SAMPLE_RATE,

    "duration":
        AUDIO_DURATION,

    "num_samples":
        NUM_SAMPLES,

    "n_mels":
        N_MELS,

    "n_fft":
        N_FFT,

    "hop_length":
        HOP_LENGTH,

    "win_length":
        WIN_LENGTH,

    "f_min":
        F_MIN,

    "f_max":
        F_MAX,

    "model_name":
        "VoiceDeepfakeCNN",

    "task":
        "binary_voice_deepfake_detection",

    "classes": {
        "0": "REAL",
        "1": "FAKE"
    }
}

torch.save(
    deployment_package,
    DEPLOYMENT_MODEL_PATH
)

print(
    "Deployment model saved:"
)

print(
    DEPLOYMENT_MODEL_PATH
)

print(
    "Size:",
    round(
        DEPLOYMENT_MODEL_PATH.stat().st_size /
        1024**2,
        2
    ),
    "MB"
)

# ============================================================
# CELL 31 — FINAL ARTIFACT SUMMARY
# ============================================================

print("=" * 70)
print("PROJECT ARTIFACTS")
print("=" * 70)

for p in OUTPUT_ROOT.rglob("*"):

    if p.is_file():

        size_mb = (
            p.stat().st_size /
            1024**2
        )

        print(
            f"{p.relative_to(OUTPUT_ROOT)}"
            f"  ({size_mb:.2f} MB)"
        )

import os

import numpy as np
import soundfile as sf
import torch
import torch.nn.functional as F
from scipy.signal import resample_poly

# ============================================================
# CONFIG
# ============================================================

MODEL_PATH = (
    DEPLOYMENT_MODEL_PATH
    if Path(DEPLOYMENT_MODEL_PATH).exists()
    else Path("/kaggle/working/voice_deepfake_detector/voice_deepfake_detector.pth")
)

SAMPLE_RATE = 16000
AUDIO_DURATION = 2.0
NUM_SAMPLES = int(SAMPLE_RATE * AUDIO_DURATION)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", DEVICE)
print("Model:", MODEL_PATH)


# ============================================================
# LOAD MODEL
# ============================================================

checkpoint = None
if Path(MODEL_PATH).exists():
    checkpoint = torch.load(
        MODEL_PATH,
        map_location=DEVICE,
        weights_only=False
    )
    print("Checkpoint loaded.")
    print("Keys:", checkpoint.keys())
else:
    print(f"Notice: Model checkpoint not found at {MODEL_PATH}.")


# ============================================================
# RECREATE MODEL
# ============================================================

model = VoiceDeepfakeCNN().to(DEVICE)

if checkpoint is not None:
    # Our deployment file should contain model_state_dict
    if "model_state_dict" in checkpoint:
        model.load_state_dict(checkpoint["model_state_dict"])
    elif "state_dict" in checkpoint:
        model.load_state_dict(checkpoint["state_dict"])
    else:
        model.load_state_dict(checkpoint)
    print("✅ Model loaded successfully.")

model.eval()

print("✅ Model loaded successfully.")


# ============================================================
# THRESHOLD
# ============================================================

if isinstance(checkpoint, dict):

    threshold = checkpoint.get(
        "threshold",
        0.5
    )

else:

    threshold = 0.5

print("Detection threshold:", threshold)


# ============================================================
# AUDIO LOADER
# ============================================================

def load_audio_for_prediction(path):
    """
    Load audio using the unified load_audio function and return a torch FloatTensor.
    """
    audio = load_audio(path, target_sr=SAMPLE_RATE, training=False)
    return torch.from_numpy(audio)


# ============================================================
# PREDICTION FUNCTION
# ============================================================

def predict_voice(audio_path):

    print("\n" + "=" * 60)
    print("VOICE DEEPFAKE DETECTION")
    print("=" * 60)

    print("File:", audio_path)

    # Load audio
    audio = load_audio_for_prediction(
        audio_path
    )

    audio = audio.unsqueeze(0).to(DEVICE)

    print("Audio shape:", audio.shape)

    # --------------------------------------------------------
    # Mel spectrogram
    # --------------------------------------------------------

    global mel_transform
    if "mel_transform" not in globals() or mel_transform is None:
        mel_transform = LogMelSpectrogram(
            sample_rate=SAMPLE_RATE,
            n_fft=N_FFT,
            hop_length=HOP_LENGTH,
            win_length=WIN_LENGTH,
            n_mels=N_MELS,
            mel_filterbank=MEL_FILTERBANK
        ).to(DEVICE)

    with torch.no_grad():

        mel = mel_transform(audio)

        # Safety
        mel = torch.nan_to_num(
            mel,
            nan=0.0,
            posinf=0.0,
            neginf=0.0
        )

        # ----------------------------------------------------
        # CNN
        # ----------------------------------------------------

        logits = model(mel)

        logits = torch.nan_to_num(
            logits,
            nan=0.0,
            posinf=20.0,
            neginf=-20.0
        )

        # ----------------------------------------------------
        # Probability
        # ----------------------------------------------------

        fake_probability = torch.sigmoid(
            logits
        ).item()

    real_probability = 1.0 - fake_probability

    # --------------------------------------------------------
    # Classification
    # --------------------------------------------------------

    if fake_probability >= threshold:

        prediction = "AI-GENERATED / FAKE"

    else:

        prediction = "REAL / BONAFIDE"

    confidence = max(
        fake_probability,
        real_probability
    )

    # --------------------------------------------------------
    # Result
    # --------------------------------------------------------

    print()
    print("RESULT")
    print("-" * 60)

    print(
        f"Fake probability : {fake_probability * 100:.2f}%"
    )

    print(
        f"Real probability : {real_probability * 100:.2f}%"
    )

    print(
        f"Confidence       : {confidence * 100:.2f}%"
    )

    print(
        f"Threshold        : {threshold:.4f}"
    )

    print()
    print("Prediction:", prediction)

    print("=" * 60)

    return {
        "file": audio_path,
        "fake_probability": fake_probability,
        "real_probability": real_probability,
        "confidence": confidence,
        "prediction": prediction
    }

